"""
Master property data pipeline — county-agnostic, browser-use only.

For each county the pipeline reads its master_data source config and runs a
single browser-use Agent to download the bulk property file(s).  The agent
task prompt is generated by Claude from the county source metadata so no
per-county prompt files are needed.

Hillsborough → downloads PARCEL_SPREADSHEET.xls, converts to CSV
Pinellas     → downloads each table in special_flags['bulk_tables'] directly as CSV

Runs WEEKLY (Sunday 01:00 UTC via cron). The full converted file goes to
MasterPropertyLoader, which partitions rows by hash-based change detection:
new parcels are inserted, changed parcels are updated set-based (with
needs_rescore / pending_sync / skip_trace_stale flags for downstream),
unchanged parcels only get their last_seen_at stamped. No deletes.

Usage:
    python -m src.scrappers.master.master_engine --county-id hillsborough --headful
    python -m src.scrappers.master.master_engine --county-id pinellas --headful
    python -m src.scrappers.master.master_engine --county-id hillsborough --headful --load-to-db
    python -m src.scrappers.master.master_engine --skip-download --load-to-db --dry-run
"""

import asyncio
import argparse
import json
import math
import sys
import traceback
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Optional

import pandas as pd

project_root = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(project_root))

from src.utils.logger import setup_logging, get_logger
from src.utils.county_config import get_county_config
from src.utils.http_helpers import STEALTH_UA, STEALTH_ARGS, apply_stealth_to_browser_use
from config.constants import BROWSER_MODEL, BROWSER_TEMPERATURE

setup_logging()
logger = get_logger(__name__)

CHUNK_SIZE = 50_000
RAW_FILE_ENCODING = "cp1252"
DBF_SIGNATURES = {0x02, 0x03, 0x04, 0x05, 0x83, 0x8B, 0x8C}


# ---------------------------------------------------------------------------
# LLM helpers
# ---------------------------------------------------------------------------

def _make_llm():
    from browser_use import ChatAnthropic
    from config.settings import get_settings
    settings = get_settings()
    return ChatAnthropic(
        model=BROWSER_MODEL,
        timeout=180,
        api_key=settings.anthropic_api_key.get_secret_value(),
        temperature=BROWSER_TEMPERATURE,
    )


def build_agent_task(source: dict, save_dir: Path) -> str:
    """
    Generate a browser-use agent task prompt from the county source config.

    Uses Claude to turn source metadata (url, description, navigation_hint,
    bulk_tables) into a clear step-by-step download task.  Falls back to a
    template if the LLM call fails.
    """
    import anthropic
    from config.settings import get_settings

    url = source["url"]
    description = source.get("description", "")
    nav_hint = source.get("navigation_hint", "") or ""
    bulk_tables = source.get("bulk_tables")

    meta = {
        "url": url,
        "description": description,
        "navigation_hint": nav_hint,
        "output_format": source.get("output_format", "csv"),
        "bulk_tables": bulk_tables,
        "save_directory": str(save_dir),
    }

    system_prompt = (
        "You generate browser-automation task instructions for a browser-use Agent. "
        "The agent is a Chromium browser controller that can click, scroll, and trigger downloads. "
        "Write a concise, step-by-step task in plain English. "
        "Be specific about file names to look for. "
        "Do NOT add any explanation outside the task text."
    )

    user_prompt = f"""Generate a browser-use agent task to download bulk property data files.

Source metadata:
{json.dumps(meta, indent=2)}

Requirements:
- The agent must navigate to the URL and download all relevant files.
- If bulk_tables is provided, download each one by name.
- If no bulk_tables, download the primary bulk property data file (largest or most prominent download link).
- Files will be saved automatically by the browser to the save_directory.
- Be explicit about what to click and what filenames to look for.
- Keep the task under 200 words.
"""

    try:
        settings = get_settings()
        client = anthropic.Anthropic(
            api_key=settings.anthropic_api_key.get_secret_value()
        )
        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=512,
            temperature=0,
            system=system_prompt,
            messages=[{"role": "user", "content": user_prompt}],
        )
        task = response.content[0].text.strip()
        logger.info(f"[LLM] Generated agent task:\n{task}")
        return task
    except Exception as e:
        logger.warning(f"[LLM] Task generation failed ({e}) — using template fallback")
        return _template_task(source, save_dir)


def _template_task(source: dict, save_dir: Path) -> str:
    """Template fallback when LLM is unavailable."""
    url = source["url"]
    nav_hint = source.get("navigation_hint", "") or ""
    bulk_tables = source.get("bulk_tables")

    if bulk_tables:
        tables_str = "\n".join(f"- {t}" for t in bulk_tables)
        return (
            f"Go to {url}.\n"
            f"{nav_hint}\n"
            f"Download the following CSV files one by one:\n{tables_str}\n"
            f"Wait for each download to complete before starting the next."
        )
    return (
        f"Go to {url}.\n"
        f"{nav_hint}\n"
        f"Find and download the main bulk property data file on the page.\n"
        f"Wait for the download to complete."
    )


# ---------------------------------------------------------------------------
# Browser-use download
# ---------------------------------------------------------------------------

async def run_browser_agent(task: str, save_dir: Path, headful: bool = False) -> bool:
    """
    Run a browser-use Agent with the given task.
    Downloads land in save_dir via Browser(downloads_path=...).
    Returns True if the agent reported done.
    """
    from browser_use import Agent, Browser

    save_dir.mkdir(parents=True, exist_ok=True)
    llm = _make_llm()

    browser = Browser(
        headless=not headful,
        downloads_path=str(save_dir),
        disable_security=True,
        user_agent=STEALTH_UA,
        ignore_default_args=["--enable-automation"],
        enable_default_extensions=True,
        minimum_wait_page_load_time=1.5,
        wait_between_actions=1.0,
        args=STEALTH_ARGS,
    )
    await browser.start()
    await apply_stealth_to_browser_use(browser)
    logger.info("[master] Stealth fingerprint patches injected")

    agent = Agent(
        task=task,
        llm=llm,
        browser=browser,
        max_failures=3,
        use_judge=False,
    )

    logger.info("[Agent] Starting browser-use agent...")
    try:
        history = await agent.run()
        done = history.is_done()
        if not done:
            logger.warning("[Agent] Agent did not complete all steps within budget")
        return done
    except Exception as e:
        logger.error(f"[Agent] Run failed: {e}")
        logger.debug(traceback.format_exc())
        return False


# ---------------------------------------------------------------------------
# Post-download helpers
# ---------------------------------------------------------------------------

def extract_zips(directory: Path) -> list[Path]:
    """
    Extract all zip files in directory and delete the zips.
    Returns list of extracted file paths.
    """
    import zipfile
    extracted = []
    for zip_path in sorted(directory.glob("*.zip"), key=lambda p: p.stat().st_size, reverse=True):
        try:
            logger.info(f"Extracting {zip_path.name}...")
            with zipfile.ZipFile(zip_path, 'r') as zf:
                for member in zf.namelist():
                    zf.extract(member, directory)
                    extracted.append(directory / member)
                    logger.info(f"  -> {member}")
            zip_path.unlink()
        except zipfile.BadZipFile:
            logger.warning(f"Skipping {zip_path.name} ({zip_path.stat().st_size} bytes) — not a valid zip, likely a duplicate/stub download. Deleting.")
            zip_path.unlink()
    return extracted


def find_table_csv(directory: Path, table_name: str) -> Optional[Path]:
    """
    Find a CSV file for table_name in directory — case-insensitive,
    allows extra suffixes like _csv or _export in the filename.
    """
    table_lower = table_name.lower()
    for f in directory.iterdir():
        if f.suffix.lower() == '.csv' and table_lower in f.stem.lower():
            return f
    return None


# ---------------------------------------------------------------------------
# File helpers
# ---------------------------------------------------------------------------

def _detect_file_type(file_path: Path) -> str:
    with open(file_path, 'rb') as fh:
        sig = fh.read(8)
    if not sig:
        raise ValueError(f"Empty file: {file_path}")
    if sig[0] in DBF_SIGNATURES:
        return 'dbf'
    if sig.startswith(b'\xD0\xCF\x11\xE0'):
        return 'xls'
    if sig.startswith(b'PK\x03\x04'):
        return 'xlsx'
    return 'text'


def _format_cell(value) -> str:
    if value is None:
        return ""
    if isinstance(value, Decimal):
        return format(value, 'f').rstrip('0').rstrip('.') or "0"
    if isinstance(value, float):
        import math as _math
        if _math.isnan(value):
            return ""
        if value.is_integer():
            return str(int(value))
    return str(value)


def _normalize_col(label: str) -> str:
    n = ''.join(c.lower() if c.isalnum() else '_' for c in str(label).strip())
    return '_'.join(filter(None, n.split('_')))


def _excel_chunks(path: Path):
    import xlrd
    book = xlrd.open_workbook(str(path), on_demand=True)
    sheet = book.sheet_by_index(0)
    header = [sheet.cell_value(0, c) for c in range(sheet.ncols)]
    buf = []
    for r in range(1, sheet.nrows):
        buf.append({header[c]: _format_cell(sheet.cell_value(r, c)) for c in range(sheet.ncols)})
        if len(buf) >= CHUNK_SIZE:
            df = pd.DataFrame(buf)
            df.columns = [_normalize_col(c) for c in df.columns]
            yield df
            buf = []
    if buf:
        df = pd.DataFrame(buf)
        df.columns = [_normalize_col(c) for c in df.columns]
        yield df
    book.release_resources()


def _dbf_chunks(path: Path):
    from dbfread import DBF
    tbl = DBF(str(path), encoding=RAW_FILE_ENCODING, ignore_missing_memofile=True)
    fields = tbl.field_names
    buf = []
    for rec in tbl:
        buf.append({f: _format_cell(rec.get(f)) for f in fields})
        if len(buf) >= CHUNK_SIZE:
            df = pd.DataFrame(buf)
            df.columns = [_normalize_col(c) for c in df.columns]
            yield df
            buf = []
    if buf:
        df = pd.DataFrame(buf)
        df.columns = [_normalize_col(c) for c in df.columns]
        yield df


def _xlsx_chunks(path: Path):
    """Read XLSX in chunks via pandas + openpyxl."""
    logger.info(f"Opening XLSX: {path}")
    for chunk in pd.read_excel(path, chunksize=CHUNK_SIZE, dtype=str, engine='openpyxl'):
        chunk.columns = [_normalize_col(c) for c in chunk.columns]
        yield chunk


def convert_to_csv(src: Path, dest_dir: Path) -> Path:
    """
    Convert XLS / XLSX / DBF to CSV. Plain CSV is copied as-is.
    Returns output CSV path.
    """
    dest_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out = dest_dir / f"master_{ts}.csv"
    ftype = _detect_file_type(src)
    logger.info(f"Converting {ftype.upper()} to CSV: {src.name}")

    if ftype == 'text':
        import shutil as _shutil
        _shutil.copy2(src, out)
        logger.info(f"Copied CSV: {out} ({out.stat().st_size / 1e6:.1f} MB)")
        return out

    if ftype == 'xls':
        reader = _excel_chunks(src)
    elif ftype == 'xlsx':
        reader = _xlsx_chunks(src)
    elif ftype == 'dbf':
        reader = _dbf_chunks(src)
    else:
        raise ValueError(f"Unsupported file type '{ftype}' for {src}")

    total = 0
    for i, chunk in enumerate(reader):
        for col in chunk.select_dtypes(include='object').columns:
            chunk[col] = chunk[col].str.strip()
        chunk.to_csv(out, mode='w' if i == 0 else 'a', index=False, header=(i == 0))
        total += len(chunk)

    logger.info(f"Converted {total:,} rows to {out} ({out.stat().st_size / 1e6:.1f} MB)")
    return out


def discover_and_convert(ref_dir: Path, staging_dir: Path) -> Optional[Path]:
    """
    Find the downloaded bulk file, extract zip if needed, convert to CSV.

    Handles every combination a county portal might deliver:
      - Plain CSV          -> use directly
      - CSV in ZIP         -> extract, use directly
      - XLS / XLSX / DBF   -> convert to CSV
      - XLS/XLSX/DBF in ZIP -> extract, then convert

    Priority: CSV > XLSX > XLS > DBF (prefer already-CSV to skip conversion).
    """
    extract_zips(ref_dir)  # no-op if no zips present

    for pattern in ['*.csv', '*.CSV', '*.xlsx', '*.XLSX', '*.xls', '*.XLS', '*.dbf', '*.DBF']:
        candidates = list(ref_dir.glob(pattern))
        if candidates:
            src = sorted(candidates, key=lambda p: p.stat().st_mtime, reverse=True)[0]
            logger.info(f"Found bulk file: {src.name} ({src.stat().st_size / 1e6:.1f} MB)")
            ftype = _detect_file_type(src)
            if ftype == 'text':
                return src  # already CSV, use in place
            return convert_to_csv(src, staging_dir)

    return None


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------

def load_to_database(csv_path: Path, county_id: str, dry_run: bool = False,
                     chunk_size: int = 10_000):
    """Load the full converted file — the loader partitions rows itself
    (insert new / update changed / stamp unchanged via hash comparison)."""
    from src.core.database import get_db_context
    from src.loaders.master import MasterPropertyLoader
    with get_db_context() as session:
        loader = MasterPropertyLoader(session, county_id=county_id)
        stats = loader.load_from_csv(str(csv_path), chunksize=chunk_size, dry_run=dry_run)
    logger.info(f"Loaded: {stats.summary()}")
    return stats


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------

async def run_master_pipeline(
    county_id: str = "hillsborough",
    skip_download: bool = False,
    load_to_db: bool = False,
    headful: bool = False,
    dry_run: bool = False,
    chunk_size: int = 10_000,
):
    cfg = get_county_config(county_id)
    source = cfg["sources"]["master_data"]
    bulk_tables = source.get("bulk_tables")  # Pinellas only

    ref_dir = Path(f"data/reference/{county_id}")
    staging_dir = Path(f"data/raw/master/{county_id}/new")

    logger.info("=" * 70)
    logger.info(f"MASTER PIPELINE — {cfg['display_name'].upper()}")
    logger.info(f"headful={headful}  load_to_db={load_to_db}  dry_run={dry_run}")
    logger.info("=" * 70)

    # ── Phase 1: Download ─────────────────────────────────────────────────
    if not skip_download:
        task = build_agent_task(source, ref_dir)
        success = await run_browser_agent(task, ref_dir, headful=headful)
        if not success:
            logger.error("Agent reported failure — check browser output")
            # Continue anyway: partial downloads may still be usable

    # ── Discover + normalize downloaded files ────────────────────────────
    if bulk_tables:
        # Multi-table county: extract zips, find each table file individually.
        # Each table may arrive as plain CSV, zipped CSV, XLS, XLSX, or DBF.
        extract_zips(ref_dir)
        downloaded = []
        for table in bulk_tables:
            csv_path = find_table_csv(ref_dir, table)
            if csv_path:
                downloaded.append(csv_path)
                logger.info(f"Found {table} -> {csv_path.name}")
            else:
                logger.warning(f"Table not found after extraction: {table}")

        logger.info(f"Found {len(downloaded)}/{len(bulk_tables)} tables in {ref_dir}")
        if not downloaded:
            logger.error("No table files found — aborting")
            return

        if load_to_db:
            for csv_path in downloaded:
                load_to_database(csv_path, county_id, dry_run=dry_run, chunk_size=chunk_size)
        else:
            logger.info("Files ready. Run with --load-to-db to load into database.")
        return

    # Single-file county: any format, possibly zipped.
    # discover_and_convert handles CSV / XLSX / XLS / DBF, plain or inside a ZIP.
    converted_csv = discover_and_convert(ref_dir, staging_dir)
    if not converted_csv:
        logger.error(f"No bulk file found in {ref_dir} — download may have failed")
        return

    # ── Phase 3: Load ─────────────────────────────────────────────────────
    # The full file goes to the loader — it partitions rows itself by hash
    # (insert new / update changed / stamp unchanged), so the old pre-load
    # dedup pass that dropped existing parcels is gone.
    if load_to_db:
        load_to_database(converted_csv, county_id, dry_run=dry_run, chunk_size=chunk_size)
    else:
        logger.info(f"Ready: {converted_csv}")
        logger.info("Run with --load-to-db to load into database.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Master Property Data Pipeline")
    parser.add_argument("--county-id", default="hillsborough")
    parser.add_argument("--skip-download", action="store_true",
                        help="Skip download, use existing file in data/reference/<county>/")
    parser.add_argument("--load-to-db", action="store_true",
                        help="Load to database after download/conversion")
    parser.add_argument("--headful", action="store_true",
                        help="Run browser in visible (headful) mode")
    parser.add_argument("--dry-run", action="store_true",
                        help="Classify and report counts but roll back all DB changes")
    parser.add_argument("--chunk-size", type=int, default=10_000,
                        help="CSV rows processed per chunk (default 10000)")

    args = parser.parse_args()
    asyncio.run(run_master_pipeline(
        county_id=args.county_id,
        skip_download=args.skip_download,
        load_to_db=args.load_to_db,
        headful=args.headful,
        dry_run=args.dry_run,
        chunk_size=args.chunk_size,
    ))
