"""add foreclosure case_status

Revision ID: 0b86033e71f3
Revises: k1l2m3n4o5p6
Create Date: 2026-04-10 11:51:17.699658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b86033e71f3'
down_revision: Union[str, Sequence[str], None] = 'k1l2m3n4o5p6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building_permits', 'is_enforcement_permit',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_building_permits_is_enforcement'), table_name='building_permits')
    op.create_index(op.f('ix_building_permits_is_enforcement_permit'), 'building_permits', ['is_enforcement_permit'], unique=False)
    op.add_column('foreclosures', sa.Column('case_status', sa.String(length=100), nullable=True))
    op.create_index('idx_foreclosure_case_status', 'foreclosures', ['case_status'], unique=False)
    op.alter_column('lead_pack_purchases', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lead_pack_purchases', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lead_pack_purchases', 'purchased_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_lead_pack_subscriber'), table_name='lead_pack_purchases')
    op.drop_constraint(op.f('uq_lead_pack_payment_intent'), 'lead_pack_purchases', type_='unique')
    op.create_index(op.f('ix_lead_pack_purchases_stripe_payment_intent_id'), 'lead_pack_purchases', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_lead_pack_purchases_subscriber_id'), 'lead_pack_purchases', ['subscriber_id'], unique=False)
    op.alter_column('legal_and_liens', 'match_confidence',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Rapidfuzz score 0-100 at time of property match',
               existing_nullable=True)
    op.alter_column('legal_and_liens', 'match_method',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='How the property was matched: legal_desc | owner_name | llm_verified | address | manual',
               existing_nullable=True)
    op.drop_index(op.f('idx_owner_name_trgm'), table_name='owners', postgresql_ops={'owner_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('platform_daily_stats', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'signals_scraped',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'signals_matched',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'signals_skipped',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'properties_scored',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'properties_with_signals',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'score_runs_total',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'leads_new',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'leads_updated',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'leads_unchanged',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'leads_qualified',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'leads_upgraded',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'tier_ultra_platinum',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'tier_platinum',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'tier_gold',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'tier_silver',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'tier_bronze',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_platform_stats_county_id'), table_name='platform_daily_stats')
    op.create_index(op.f('ix_platform_daily_stats_county_id'), 'platform_daily_stats', ['county_id'], unique=False)
    op.create_index(op.f('ix_platform_daily_stats_run_date'), 'platform_daily_stats', ['run_date'], unique=False)
    op.drop_index(op.f('idx_property_address_trgm'), table_name='properties', postgresql_ops={'address': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_property_legal_desc_trgm'), table_name='properties', postgresql_ops={'legal_description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('scraper_run_stats', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'total_scraped',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'matched',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'unmatched',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'skipped',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'scored',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'run_success',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_run_stats_county_id'), table_name='scraper_run_stats')
    op.drop_index(op.f('idx_run_stats_run_date'), table_name='scraper_run_stats')
    op.drop_index(op.f('idx_run_stats_source_type'), table_name='scraper_run_stats')
    op.create_index(op.f('ix_scraper_run_stats_county_id'), 'scraper_run_stats', ['county_id'], unique=False)
    op.create_index(op.f('ix_scraper_run_stats_run_date'), 'scraper_run_stats', ['run_date'], unique=False)
    op.create_index(op.f('ix_scraper_run_stats_source_type'), 'scraper_run_stats', ['source_type'], unique=False)
    op.alter_column('sent_leads', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('unmatched_records', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('unmatched_records', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('unmatched_records', 'match_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unmatched_records', 'match_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'unmatched'::character varying"),
               existing_nullable=False)
    op.alter_column('unmatched_records', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('unmatched_records', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'hillsborough'::character varying"),
               existing_nullable=False)
    op.alter_column('sent_leads', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_scraper_run_stats_source_type'), table_name='scraper_run_stats')
    op.drop_index(op.f('ix_scraper_run_stats_run_date'), table_name='scraper_run_stats')
    op.drop_index(op.f('ix_scraper_run_stats_county_id'), table_name='scraper_run_stats')
    op.create_index(op.f('idx_run_stats_source_type'), 'scraper_run_stats', ['source_type'], unique=False)
    op.create_index(op.f('idx_run_stats_run_date'), 'scraper_run_stats', ['run_date'], unique=False)
    op.create_index(op.f('idx_run_stats_county_id'), 'scraper_run_stats', ['county_id'], unique=False)
    op.alter_column('scraper_run_stats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'run_success',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'scored',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'skipped',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'unmatched',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'matched',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'total_scraped',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('scraper_run_stats', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'hillsborough'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('idx_property_legal_desc_trgm'), 'properties', ['legal_description'], unique=False, postgresql_ops={'legal_description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_property_address_trgm'), 'properties', ['address'], unique=False, postgresql_ops={'address': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_platform_daily_stats_run_date'), table_name='platform_daily_stats')
    op.drop_index(op.f('ix_platform_daily_stats_county_id'), table_name='platform_daily_stats')
    op.create_index(op.f('idx_platform_stats_county_id'), 'platform_daily_stats', ['county_id'], unique=False)
    op.alter_column('platform_daily_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'tier_bronze',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'tier_silver',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'tier_gold',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'tier_platinum',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'tier_ultra_platinum',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'leads_upgraded',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'leads_qualified',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'leads_unchanged',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'leads_updated',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'leads_new',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'score_runs_total',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'properties_with_signals',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'properties_scored',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'signals_skipped',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'signals_matched',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'signals_scraped',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('platform_daily_stats', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'hillsborough'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('idx_owner_name_trgm'), 'owners', ['owner_name'], unique=False, postgresql_ops={'owner_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('legal_and_liens', 'match_method',
               existing_type=sa.VARCHAR(length=30),
               comment='How the property was matched: legal_desc | owner_name | llm_verified | address | manual',
               existing_nullable=True)
    op.alter_column('legal_and_liens', 'match_confidence',
               existing_type=sa.INTEGER(),
               comment='Rapidfuzz score 0-100 at time of property match',
               existing_nullable=True)
    op.drop_index(op.f('ix_lead_pack_purchases_subscriber_id'), table_name='lead_pack_purchases')
    op.drop_index(op.f('ix_lead_pack_purchases_stripe_payment_intent_id'), table_name='lead_pack_purchases')
    op.create_unique_constraint(op.f('uq_lead_pack_payment_intent'), 'lead_pack_purchases', ['stripe_payment_intent_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_lead_pack_subscriber'), 'lead_pack_purchases', ['subscriber_id'], unique=False)
    op.alter_column('lead_pack_purchases', 'purchased_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('lead_pack_purchases', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('lead_pack_purchases', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'hillsborough'::character varying"),
               existing_nullable=False)
    op.drop_index('idx_foreclosure_case_status', table_name='foreclosures')
    op.drop_column('foreclosures', 'case_status')
    op.drop_index(op.f('ix_building_permits_is_enforcement_permit'), table_name='building_permits')
    op.create_index(op.f('idx_building_permits_is_enforcement'), 'building_permits', ['is_enforcement_permit'], unique=False)
    op.alter_column('building_permits', 'is_enforcement_permit',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
