"""add_compliance_observability_tables

Revision ID: 2d2dd1371479
Revises: o5p6q7r8s9t0
Create Date: 2026-04-21 12:05:06.333289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d2dd1371479'
down_revision: Union[str, Sequence[str], None] = 'o5p6q7r8s9t0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_dead_letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint("reason IN ('opt_out', 'delivery_failed', 'error', 'unresolvable')", name='check_dlq_reason'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dlq_reviewed', 'sms_dead_letters', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_sms_dead_letters_phone'), 'sms_dead_letters', ['phone'], unique=False)
    op.create_table('sms_opt_outs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('keyword_used', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_opt_outs_phone'), 'sms_opt_outs', ['phone'], unique=True)
    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('task_type', sa.String(length=60), nullable=True),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("service IN ('claude', 'twilio', 'stripe')", name='check_api_service'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_usage_service_created', 'api_usage_logs', ['service', 'created_at'], unique=False)
    op.create_index('idx_api_usage_task_created', 'api_usage_logs', ['task_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_subscriber_id'), 'api_usage_logs', ['subscriber_id'], unique=False)
    op.alter_column('ab_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_ab_assignment_subscriber'), table_name='ab_assignments')
    op.drop_index(op.f('idx_ab_assignment_test'), table_name='ab_assignments')
    op.create_index(op.f('ix_ab_assignments_subscriber_id'), 'ab_assignments', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_ab_assignments_test_id'), 'ab_assignments', ['test_id'], unique=False)
    op.alter_column('ab_tests', 'traffic_pct',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ab_tests', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ab_tests', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('deal_outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_deal_outcome_property'), table_name='deal_outcomes')
    op.drop_index(op.f('idx_deal_outcome_subscriber'), table_name='deal_outcomes')
    op.create_index(op.f('ix_deal_outcomes_property_id'), 'deal_outcomes', ['property_id'], unique=False)
    op.create_index(op.f('ix_deal_outcomes_subscriber_id'), 'deal_outcomes', ['subscriber_id'], unique=False)
    op.alter_column('learning_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_learning_card_date'), table_name='learning_cards')
    op.create_index(op.f('ix_learning_cards_card_date'), 'learning_cards', ['card_date'], unique=False)
    op.alter_column('message_outcomes', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('message_outcomes', 'conversion_within_4h',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('message_outcomes', 'conversion_within_24h',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('message_outcomes', 'conversion_within_48h',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('message_outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_msg_outcome_subscriber'), table_name='message_outcomes')
    op.drop_index(op.f('idx_msg_outcome_variant'), table_name='message_outcomes')
    op.create_index(op.f('ix_message_outcomes_subscriber_id'), 'message_outcomes', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_message_outcomes_variant_id'), 'message_outcomes', ['variant_id'], unique=False)
    op.alter_column('referral_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('referral_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_referral_code'), table_name='referral_events')
    op.drop_index(op.f('idx_referral_referee'), table_name='referral_events')
    op.drop_index(op.f('idx_referral_referrer'), table_name='referral_events')
    op.create_index(op.f('ix_referral_events_referee_subscriber_id'), 'referral_events', ['referee_subscriber_id'], unique=False)
    op.create_index(op.f('ix_referral_events_referral_code'), 'referral_events', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referral_events_referrer_subscriber_id'), 'referral_events', ['referrer_subscriber_id'], unique=False)
    op.alter_column('subscribers', 'has_saved_card',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscribers', 'auto_mode_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_subscriber_referral_code'), table_name='subscribers')
    op.drop_index(op.f('uq_subscriber_email_vertical_active'), table_name='subscribers', postgresql_where="((status)::text = ANY ((ARRAY['active'::character varying, 'grace'::character varying])::text[]))")
    op.drop_constraint(op.f('uq_subscriber_referral_code'), 'subscribers', type_='unique')
    op.create_index(op.f('ix_subscribers_referral_code'), 'subscribers', ['referral_code'], unique=True)
    op.alter_column('user_segments', 'revenue_signal_score',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_segments', 'last_classified_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_segments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_segments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_user_segment_subscriber'), table_name='user_segments')
    op.drop_constraint(op.f('user_segments_subscriber_id_key'), 'user_segments', type_='unique')
    op.create_index(op.f('ix_user_segments_subscriber_id'), 'user_segments', ['subscriber_id'], unique=True)
    op.alter_column('wallet_balances', 'credits_remaining',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wallet_balances', 'credits_used_total',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wallet_balances', 'auto_reload_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wallet_balances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wallet_balances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_wallet_balance_subscriber'), table_name='wallet_balances')
    op.drop_constraint(op.f('wallet_balances_subscriber_id_key'), 'wallet_balances', type_='unique')
    op.create_index(op.f('ix_wallet_balances_subscriber_id'), 'wallet_balances', ['subscriber_id'], unique=True)
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_wallet_txn_stripe_charge'), table_name='wallet_transactions')
    op.drop_index(op.f('idx_wallet_txn_subscriber'), table_name='wallet_transactions')
    op.drop_index(op.f('idx_wallet_txn_wallet'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_transactions_stripe_charge_id'), 'wallet_transactions', ['stripe_charge_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_subscriber_id'), 'wallet_transactions', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_subscriber_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_stripe_charge_id'), table_name='wallet_transactions')
    op.create_index(op.f('idx_wallet_txn_wallet'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('idx_wallet_txn_subscriber'), 'wallet_transactions', ['subscriber_id'], unique=False)
    op.create_index(op.f('idx_wallet_txn_stripe_charge'), 'wallet_transactions', ['stripe_charge_id'], unique=False)
    op.alter_column('wallet_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_wallet_balances_subscriber_id'), table_name='wallet_balances')
    op.create_unique_constraint(op.f('wallet_balances_subscriber_id_key'), 'wallet_balances', ['subscriber_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_wallet_balance_subscriber'), 'wallet_balances', ['subscriber_id'], unique=False)
    op.alter_column('wallet_balances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('wallet_balances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('wallet_balances', 'auto_reload_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('wallet_balances', 'credits_used_total',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('wallet_balances', 'credits_remaining',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_segments_subscriber_id'), table_name='user_segments')
    op.create_unique_constraint(op.f('user_segments_subscriber_id_key'), 'user_segments', ['subscriber_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_segment_subscriber'), 'user_segments', ['subscriber_id'], unique=False)
    op.alter_column('user_segments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_segments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_segments', 'last_classified_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_segments', 'revenue_signal_score',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_index(op.f('ix_subscribers_referral_code'), table_name='subscribers')
    op.create_unique_constraint(op.f('uq_subscriber_referral_code'), 'subscribers', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_subscriber_email_vertical_active'), 'subscribers', [sa.literal_column('lower(email::text)'), 'vertical', 'county_id'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['active'::character varying, 'grace'::character varying])::text[]))")
    op.create_index(op.f('idx_subscriber_referral_code'), 'subscribers', ['referral_code'], unique=False)
    op.alter_column('subscribers', 'auto_mode_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('subscribers', 'has_saved_card',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_referral_events_referrer_subscriber_id'), table_name='referral_events')
    op.drop_index(op.f('ix_referral_events_referral_code'), table_name='referral_events')
    op.drop_index(op.f('ix_referral_events_referee_subscriber_id'), table_name='referral_events')
    op.create_index(op.f('idx_referral_referrer'), 'referral_events', ['referrer_subscriber_id'], unique=False)
    op.create_index(op.f('idx_referral_referee'), 'referral_events', ['referee_subscriber_id'], unique=False)
    op.create_index(op.f('idx_referral_code'), 'referral_events', ['referral_code'], unique=False)
    op.alter_column('referral_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('referral_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_message_outcomes_variant_id'), table_name='message_outcomes')
    op.drop_index(op.f('ix_message_outcomes_subscriber_id'), table_name='message_outcomes')
    op.create_index(op.f('idx_msg_outcome_variant'), 'message_outcomes', ['variant_id'], unique=False)
    op.create_index(op.f('idx_msg_outcome_subscriber'), 'message_outcomes', ['subscriber_id'], unique=False)
    op.alter_column('message_outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('message_outcomes', 'conversion_within_48h',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('message_outcomes', 'conversion_within_24h',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('message_outcomes', 'conversion_within_4h',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('message_outcomes', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_learning_cards_card_date'), table_name='learning_cards')
    op.create_index(op.f('idx_learning_card_date'), 'learning_cards', ['card_date'], unique=False)
    op.alter_column('learning_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_deal_outcomes_subscriber_id'), table_name='deal_outcomes')
    op.drop_index(op.f('ix_deal_outcomes_property_id'), table_name='deal_outcomes')
    op.create_index(op.f('idx_deal_outcome_subscriber'), 'deal_outcomes', ['subscriber_id'], unique=False)
    op.create_index(op.f('idx_deal_outcome_property'), 'deal_outcomes', ['property_id'], unique=False)
    op.alter_column('deal_outcomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('ab_tests', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('ab_tests', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('ab_tests', 'traffic_pct',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.drop_index(op.f('ix_ab_assignments_test_id'), table_name='ab_assignments')
    op.drop_index(op.f('ix_ab_assignments_subscriber_id'), table_name='ab_assignments')
    op.create_index(op.f('idx_ab_assignment_test'), 'ab_assignments', ['test_id'], unique=False)
    op.create_index(op.f('idx_ab_assignment_subscriber'), 'ab_assignments', ['subscriber_id'], unique=False)
    op.alter_column('ab_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_api_usage_logs_subscriber_id'), table_name='api_usage_logs')
    op.drop_index('idx_api_usage_task_created', table_name='api_usage_logs')
    op.drop_index('idx_api_usage_service_created', table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    op.drop_index(op.f('ix_sms_opt_outs_phone'), table_name='sms_opt_outs')
    op.drop_table('sms_opt_outs')
    op.drop_index(op.f('ix_sms_dead_letters_phone'), table_name='sms_dead_letters')
    op.drop_index('idx_dlq_reviewed', table_name='sms_dead_letters')
    op.drop_table('sms_dead_letters')
    # ### end Alembic commands ###
