"""add ori columns to county_sources

Revision ID: 369c1a7319a8
Revises: fa011_column_mapping_extras
Create Date: 2026-05-07 16:04:41.907777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '369c1a7319a8'
down_revision: Union[str, Sequence[str], None] = 'fa011_column_mapping_extras'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('county_column_mappings', 'mapped_by',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               comment=None,
               existing_comment='Who produced this mapping: llm or human',
               existing_nullable=True)
    op.alter_column('county_column_mappings', 'sample_rows',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='First 3-5 rows of source data — shown in admin mapping UI',
               existing_nullable=True)
    op.alter_column('county_column_mappings', 'reject_feedback',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Admin feedback on why the mapping was rejected — passed to LLM on re-map',
               existing_nullable=True)
    op.add_column('county_sources', sa.Column('ori_column_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('county_sources', sa.Column('ori_book_page_col', sa.String(length=50), nullable=True))
    op.add_column('county_sources', sa.Column('ori_doc_type_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('county_sources', 'ori_doc_type_map')
    op.drop_column('county_sources', 'ori_book_page_col')
    op.drop_column('county_sources', 'ori_column_map')
    op.alter_column('county_column_mappings', 'reject_feedback',
               existing_type=sa.TEXT(),
               comment='Admin feedback on why the mapping was rejected — passed to LLM on re-map',
               existing_nullable=True)
    op.alter_column('county_column_mappings', 'sample_rows',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='First 3-5 rows of source data — shown in admin mapping UI',
               existing_nullable=True)
    op.alter_column('county_column_mappings', 'mapped_by',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'llm'::character varying"),
               comment='Who produced this mapping: llm or human',
               existing_nullable=True)
    # ### end Alembic commands ###
