"""add updated_at to scraper_run_stats

Revision ID: 4dd4cc27d8a9
Revises: fa026_drop_ec_ghl_cols
Create Date: 2026-05-20 13:51:56.052832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dd4cc27d8a9'
down_revision: Union[str, Sequence[str], None] = 'fa026_drop_ec_ghl_cols'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distress_scores_backup_today_v2')
    op.drop_table('sync_status_backup_today_v2')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_table('checkpoint_migrations')
    op.alter_column('agent_decisions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_decisions', 'tokens_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_decisions', 'cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bundle_purchases', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bundle_purchases', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bundle_purchases', 'credits_awarded',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bundle_purchases', 'purchased_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('idx_bundle_purchase_intent'), table_name='bundle_purchases')
    op.create_index(op.f('ix_bundle_purchases_stripe_payment_intent_id'), 'bundle_purchases', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_bundle_purchases_subscriber_id'), 'bundle_purchases', ['subscriber_id'], unique=False)
    op.alter_column('counties', 'parcel_id_format',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('counties', 'city_filer_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('counties', 'code_lien_type_map',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('counties', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('counties', 'address_city_tokens')
    op.alter_column('county_column_mappings', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('county_column_mappings', 'mapped_by',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('county_column_mappings_source_id_fkey'), 'county_column_mappings', type_='foreignkey')
    op.create_foreign_key(None, 'county_column_mappings', 'county_sources', ['source_id'], ['id'])
    op.alter_column('county_launch_audit', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('county_launch_audit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('county_sources', 'date_range_available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('county_sources', 'frequency',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('county_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('county_sources', 'special_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('county_sources_county_id_fkey'), 'county_sources', type_='foreignkey')
    op.create_foreign_key(None, 'county_sources', 'counties', ['county_id'], ['county_id'])
    op.alter_column('dbpr_contacts', 'state',
               existing_type=sa.VARCHAR(length=5),
               server_default=None,
               existing_nullable=True)
    op.alter_column('dbpr_contacts', 'data_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dbpr_contacts', 'enrichment_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dbpr_contacts', 'enrichment_attempted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('dbpr_contacts', 'email_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dbpr_contacts', 'email_sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('dbpr_contacts', 'signed_up_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('dbpr_contacts', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('dbpr_contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('dbpr_contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('dbpr_contacts_license_number_key'), 'dbpr_contacts', type_='unique')
    op.drop_index(op.f('ix_dbpr_county_id'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_county_vertical'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_email_status'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_enrichment_status'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_last_synced'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_license_number'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_subscriber_id'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_vertical'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_zip_code'), table_name='dbpr_contacts')
    op.create_index('idx_dbpr_county_vertical', 'dbpr_contacts', ['county_id', 'vertical'], unique=False)
    op.create_index('idx_dbpr_email_status', 'dbpr_contacts', ['email_status'], unique=False)
    op.create_index('idx_dbpr_enrichment_status', 'dbpr_contacts', ['enrichment_status'], unique=False)
    op.create_index('idx_dbpr_last_synced', 'dbpr_contacts', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_dbpr_contacts_county_id'), 'dbpr_contacts', ['county_id'], unique=False)
    op.create_index(op.f('ix_dbpr_contacts_license_number'), 'dbpr_contacts', ['license_number'], unique=True)
    op.create_index(op.f('ix_dbpr_contacts_subscriber_id'), 'dbpr_contacts', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_dbpr_contacts_vertical'), 'dbpr_contacts', ['vertical'], unique=False)
    op.create_index(op.f('ix_dbpr_contacts_zip_code'), 'dbpr_contacts', ['zip_code'], unique=False)
    op.alter_column('enrichment_usage_logs', 'cost_cents',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('enrichment_usage_logs', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('enrichment_usage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_enrichment_created_at'), table_name='enrichment_usage_logs')
    op.drop_index(op.f('ix_enrichment_property_id'), table_name='enrichment_usage_logs')
    op.drop_index(op.f('ix_enrichment_subscriber_id'), table_name='enrichment_usage_logs')
    op.create_index(op.f('ix_enrichment_usage_logs_created_at'), 'enrichment_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_enrichment_usage_logs_property_id'), 'enrichment_usage_logs', ['property_id'], unique=False)
    op.create_index(op.f('ix_enrichment_usage_logs_subscriber_id'), 'enrichment_usage_logs', ['subscriber_id'], unique=False)
    op.alter_column('expansion_candidates', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('expansion_candidates', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('expansion_candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('human_close_escalations', 'routed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('human_close_escalations', 'post_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('human_close_escalations', 'target_tier_price_cents',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_hce_retry'), table_name='human_close_escalations', postgresql_where='((posted_at IS NULL) AND (post_attempts < 3))')
    op.alter_column('manual_action_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('nws_alerts', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('nws_alerts', 'storm_pack_triggered',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('nws_alerts', 'cora_urgency_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('nws_alerts', 'subscriber_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_nws_alerts_affected_zips_gin'), table_name='nws_alerts', postgresql_using='gin')
    op.drop_index(op.f('ix_nws_alerts_event_processed'), table_name='nws_alerts')
    op.drop_constraint(op.f('nws_alerts_alert_id_key'), 'nws_alerts', type_='unique')
    op.create_index('idx_nws_alerts_affected_zips', 'nws_alerts', ['affected_zips'], unique=False, postgresql_using='gin')
    op.create_index('idx_nws_alerts_event_processed', 'nws_alerts', ['event', 'processed_at'], unique=False)
    op.alter_column('partner_subscriptions', 'max_zips',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('partner_subscriptions', 'activated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_partner_sub'), table_name='partner_subscriptions')
    op.alter_column('phone_deliverability_snapshots', 'tier_filter',
               existing_type=sa.VARCHAR(length=40),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'lookups_cached',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'lookups_attempted',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'lookups_succeeded',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'mobile_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'voip_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'landline_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'unknown_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'no_phone_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'vendor',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'cost_cents',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('playwright_code_history', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('premium_purchases', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('premium_purchases', 'purchased_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_premium_stripe_charge_id'), table_name='premium_purchases')
    op.drop_constraint(op.f('uq_premium_purchase_pi'), 'premium_purchases', type_='unique')
    op.drop_index(op.f('ix_premium_purchases_stripe_payment_intent_id'), table_name='premium_purchases')
    op.create_index(op.f('ix_premium_purchases_stripe_payment_intent_id'), 'premium_purchases', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_premium_purchases_stripe_charge_id'), 'premium_purchases', ['stripe_charge_id'], unique=False)
    op.alter_column('referral_forward_copy', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('referral_milestone_awards', 'awarded_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_referral_milestone_referrer'), table_name='referral_milestone_awards')
    op.create_index(op.f('ix_referral_milestone_awards_referrer_subscriber_id'), 'referral_milestone_awards', ['referrer_subscriber_id'], unique=False)
    op.alter_column('referral_teams', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('referral_teams', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sandbox_outbox', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sandbox_outbox', 'compliance_allowed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sandbox_outbox', 'would_have_delivered',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sandbox_outbox', 'sandbox_flag',
               existing_type=sa.VARCHAR(length=40),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sandbox_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scraper_alert_log', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.add_column('scraper_run_stats', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_sent_leads_pi_id'), table_name='sent_leads')
    op.create_index(op.f('ix_sent_leads_stripe_payment_intent_id'), 'sent_leads', ['stripe_payment_intent_id'], unique=False)
    op.drop_index(op.f('idx_sms_opt_in_phone'), table_name='sms_opt_ins')
    op.drop_constraint(op.f('sms_opt_ins_phone_key'), 'sms_opt_ins', type_='unique')
    op.create_index(op.f('ix_sms_opt_ins_phone'), 'sms_opt_ins', ['phone'], unique=True)
    op.create_index(op.f('ix_sms_opt_ins_subscriber_id'), 'sms_opt_ins', ['subscriber_id'], unique=False)
    op.alter_column('sms_opt_outs', 'source',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sms_send_logs', 'vendor',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_sub_lock_candidate'), table_name='subscribers', postgresql_where='(lock_candidate_at IS NOT NULL)')
    op.drop_index(op.f('idx_sub_paused'), table_name='subscribers', postgresql_where='(paused_at IS NOT NULL)')
    op.drop_index(op.f('idx_subscriber_signup_source'), table_name='subscribers')
    op.drop_index(op.f('idx_subscribers_phone'), table_name='subscribers')
    op.drop_constraint(op.f('uq_subscribers_phone'), 'subscribers', type_='unique')
    op.create_index(op.f('ix_subscribers_phone'), 'subscribers', ['phone'], unique=True)
    op.create_index(op.f('ix_subscribers_signup_source'), 'subscribers', ['signup_source'], unique=False)
    op.alter_column('wallet_push_offers', 'offered_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_wallet_push_offers_decision'), table_name='wallet_push_offers')
    op.drop_index(op.f('idx_wallet_push_offers_subscription'), table_name='wallet_push_offers')
    op.create_index(op.f('ix_wallet_push_offers_decision_id'), 'wallet_push_offers', ['decision_id'], unique=False)
    op.create_index(op.f('ix_wallet_push_offers_stripe_subscription_id'), 'wallet_push_offers', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_wallet_push_offers_subscriber_id'), 'wallet_push_offers', ['subscriber_id'], unique=False)
    op.alter_column('webhook_events', 'direction',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('webhook_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'received'::character varying"),
               existing_nullable=False)
    op.alter_column('webhook_events', 'direction',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'inbound'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_wallet_push_offers_subscriber_id'), table_name='wallet_push_offers')
    op.drop_index(op.f('ix_wallet_push_offers_stripe_subscription_id'), table_name='wallet_push_offers')
    op.drop_index(op.f('ix_wallet_push_offers_decision_id'), table_name='wallet_push_offers')
    op.create_index(op.f('idx_wallet_push_offers_subscription'), 'wallet_push_offers', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('idx_wallet_push_offers_decision'), 'wallet_push_offers', ['decision_id'], unique=False)
    op.alter_column('wallet_push_offers', 'offered_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_subscribers_signup_source'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_phone'), table_name='subscribers')
    op.create_unique_constraint(op.f('uq_subscribers_phone'), 'subscribers', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_subscribers_phone'), 'subscribers', ['phone'], unique=False)
    op.create_index(op.f('idx_subscriber_signup_source'), 'subscribers', ['signup_source'], unique=False)
    op.create_index(op.f('idx_sub_paused'), 'subscribers', ['paused_at'], unique=False, postgresql_where='(paused_at IS NOT NULL)')
    op.create_index(op.f('idx_sub_lock_candidate'), 'subscribers', ['lock_candidate_at'], unique=False, postgresql_where='(lock_candidate_at IS NOT NULL)')
    op.alter_column('sms_send_logs', 'vendor',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'telnyx'::character varying"),
               existing_nullable=False)
    op.alter_column('sms_opt_outs', 'source',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'inbound_sms'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_sms_opt_ins_subscriber_id'), table_name='sms_opt_ins')
    op.drop_index(op.f('ix_sms_opt_ins_phone'), table_name='sms_opt_ins')
    op.create_unique_constraint(op.f('sms_opt_ins_phone_key'), 'sms_opt_ins', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sms_opt_in_phone'), 'sms_opt_ins', ['phone'], unique=False)
    op.drop_index(op.f('ix_sent_leads_stripe_payment_intent_id'), table_name='sent_leads')
    op.create_index(op.f('idx_sent_leads_pi_id'), 'sent_leads', ['stripe_payment_intent_id'], unique=False)
    op.drop_column('scraper_run_stats', 'updated_at')
    op.alter_column('scraper_alert_log', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'hillsborough'::character varying"),
               existing_nullable=False)
    op.alter_column('sandbox_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('sandbox_outbox', 'sandbox_flag',
               existing_type=sa.VARCHAR(length=40),
               server_default=sa.text("'twilio_sandbox'::character varying"),
               existing_nullable=False)
    op.alter_column('sandbox_outbox', 'would_have_delivered',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('sandbox_outbox', 'compliance_allowed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('sandbox_outbox', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('referral_teams', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('referral_teams', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_referral_milestone_awards_referrer_subscriber_id'), table_name='referral_milestone_awards')
    op.create_index(op.f('idx_referral_milestone_referrer'), 'referral_milestone_awards', ['referrer_subscriber_id'], unique=False)
    op.alter_column('referral_milestone_awards', 'awarded_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('referral_forward_copy', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_premium_purchases_stripe_charge_id'), table_name='premium_purchases')
    op.drop_index(op.f('ix_premium_purchases_stripe_payment_intent_id'), table_name='premium_purchases')
    op.create_index(op.f('ix_premium_purchases_stripe_payment_intent_id'), 'premium_purchases', ['stripe_payment_intent_id'], unique=False)
    op.create_unique_constraint(op.f('uq_premium_purchase_pi'), 'premium_purchases', ['stripe_payment_intent_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_premium_stripe_charge_id'), 'premium_purchases', ['stripe_charge_id'], unique=False)
    op.alter_column('premium_purchases', 'purchased_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('premium_purchases', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('playwright_code_history', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'cost_cents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('phone_deliverability_snapshots', 'vendor',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'telnyx'::character varying"),
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'no_phone_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'unknown_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'landline_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'voip_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'mobile_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'lookups_succeeded',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'lookups_attempted',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'lookups_cached',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('phone_deliverability_snapshots', 'tier_filter',
               existing_type=sa.VARCHAR(length=40),
               server_default=sa.text("'gold_plus'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('idx_partner_sub'), 'partner_subscriptions', ['subscriber_id'], unique=False)
    op.alter_column('partner_subscriptions', 'activated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('partner_subscriptions', 'max_zips',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.drop_index('idx_nws_alerts_event_processed', table_name='nws_alerts')
    op.drop_index('idx_nws_alerts_affected_zips', table_name='nws_alerts', postgresql_using='gin')
    op.create_unique_constraint(op.f('nws_alerts_alert_id_key'), 'nws_alerts', ['alert_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_nws_alerts_event_processed'), 'nws_alerts', ['event', 'processed_at'], unique=False)
    op.create_index(op.f('ix_nws_alerts_affected_zips_gin'), 'nws_alerts', ['affected_zips'], unique=False, postgresql_using='gin')
    op.alter_column('nws_alerts', 'subscriber_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('nws_alerts', 'cora_urgency_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('nws_alerts', 'storm_pack_triggered',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('nws_alerts', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'hillsborough'::character varying"),
               existing_nullable=False)
    op.alter_column('manual_action_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('idx_hce_retry'), 'human_close_escalations', ['post_attempts', 'routed_at'], unique=False, postgresql_where='((posted_at IS NULL) AND (post_attempts < 3))')
    op.alter_column('human_close_escalations', 'target_tier_price_cents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('human_close_escalations', 'post_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('human_close_escalations', 'routed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('expansion_candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('expansion_candidates', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'queued'::character varying"),
               existing_nullable=False)
    op.alter_column('expansion_candidates', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.drop_index(op.f('ix_enrichment_usage_logs_subscriber_id'), table_name='enrichment_usage_logs')
    op.drop_index(op.f('ix_enrichment_usage_logs_property_id'), table_name='enrichment_usage_logs')
    op.drop_index(op.f('ix_enrichment_usage_logs_created_at'), table_name='enrichment_usage_logs')
    op.create_index(op.f('ix_enrichment_subscriber_id'), 'enrichment_usage_logs', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_enrichment_property_id'), 'enrichment_usage_logs', ['property_id'], unique=False)
    op.create_index(op.f('ix_enrichment_created_at'), 'enrichment_usage_logs', ['created_at'], unique=False)
    op.alter_column('enrichment_usage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('enrichment_usage_logs', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('enrichment_usage_logs', 'cost_cents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_dbpr_contacts_zip_code'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_contacts_vertical'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_contacts_subscriber_id'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_contacts_license_number'), table_name='dbpr_contacts')
    op.drop_index(op.f('ix_dbpr_contacts_county_id'), table_name='dbpr_contacts')
    op.drop_index('idx_dbpr_last_synced', table_name='dbpr_contacts')
    op.drop_index('idx_dbpr_enrichment_status', table_name='dbpr_contacts')
    op.drop_index('idx_dbpr_email_status', table_name='dbpr_contacts')
    op.drop_index('idx_dbpr_county_vertical', table_name='dbpr_contacts')
    op.create_index(op.f('ix_dbpr_zip_code'), 'dbpr_contacts', ['zip_code'], unique=False)
    op.create_index(op.f('ix_dbpr_vertical'), 'dbpr_contacts', ['vertical'], unique=False)
    op.create_index(op.f('ix_dbpr_subscriber_id'), 'dbpr_contacts', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_dbpr_license_number'), 'dbpr_contacts', ['license_number'], unique=True)
    op.create_index(op.f('ix_dbpr_last_synced'), 'dbpr_contacts', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_dbpr_enrichment_status'), 'dbpr_contacts', ['enrichment_status'], unique=False)
    op.create_index(op.f('ix_dbpr_email_status'), 'dbpr_contacts', ['email_status'], unique=False)
    op.create_index(op.f('ix_dbpr_county_vertical'), 'dbpr_contacts', ['county_id', 'vertical'], unique=False)
    op.create_index(op.f('ix_dbpr_county_id'), 'dbpr_contacts', ['county_id'], unique=False)
    op.create_unique_constraint(op.f('dbpr_contacts_license_number_key'), 'dbpr_contacts', ['license_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('dbpr_contacts', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('dbpr_contacts', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('dbpr_contacts', 'last_synced_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('dbpr_contacts', 'signed_up_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('dbpr_contacts', 'email_sent_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('dbpr_contacts', 'email_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'not_sent'::character varying"),
               existing_nullable=False)
    op.alter_column('dbpr_contacts', 'enrichment_attempted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('dbpr_contacts', 'enrichment_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('dbpr_contacts', 'data_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'certified'::character varying"),
               existing_nullable=False)
    op.alter_column('dbpr_contacts', 'state',
               existing_type=sa.VARCHAR(length=5),
               server_default=sa.text("'FL'::character varying"),
               existing_nullable=True)
    op.drop_constraint(None, 'county_sources', type_='foreignkey')
    op.create_foreign_key(op.f('county_sources_county_id_fkey'), 'county_sources', 'counties', ['county_id'], ['county_id'], ondelete='CASCADE')
    op.alter_column('county_sources', 'special_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('county_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('county_sources', 'frequency',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'daily'::character varying"),
               existing_nullable=True)
    op.alter_column('county_sources', 'date_range_available',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('county_launch_audit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('county_launch_audit', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'county_column_mappings', type_='foreignkey')
    op.create_foreign_key(op.f('county_column_mappings_source_id_fkey'), 'county_column_mappings', 'county_sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.alter_column('county_column_mappings', 'mapped_by',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'llm'::character varying"),
               existing_nullable=True)
    op.alter_column('county_column_mappings', 'is_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.add_column('counties', sa.Column('address_city_tokens', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.alter_column('counties', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('counties', 'code_lien_type_map',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('counties', 'city_filer_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('counties', 'parcel_id_format',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'folio'::character varying"),
               existing_nullable=True)
    op.drop_index(op.f('ix_bundle_purchases_subscriber_id'), table_name='bundle_purchases')
    op.drop_index(op.f('ix_bundle_purchases_stripe_payment_intent_id'), table_name='bundle_purchases')
    op.create_index(op.f('idx_bundle_purchase_intent'), 'bundle_purchases', ['stripe_payment_intent_id'], unique=True)
    op.alter_column('bundle_purchases', 'purchased_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bundle_purchases', 'credits_awarded',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('bundle_purchases', 'county_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'hillsborough'::character varying"),
               existing_nullable=False)
    op.alter_column('bundle_purchases', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('agent_decisions', 'cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('agent_decisions', 'tokens_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('agent_decisions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('sync_status_backup_today_v2',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_crm_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('gohighlevel_contact_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('distress_scores_backup_today_v2',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('final_cds_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('lead_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('distress_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('urgency_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('multiplier', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('factor_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('qualified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('vertical_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('county_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('scoring_run_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
