"""add hcpa enrichment fields and tax_payment_history

Revision ID: 7baab3a62175
Revises: fa030_merge_foreclosures_defendant
Create Date: 2026-05-22 13:34:18.998942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7baab3a62175'
down_revision: Union[str, Sequence[str], None] = 'fa030_merge_foreclosures_defendant'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_payment_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('bill_type', sa.String(length=50), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('days_late', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.String(length=50), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'tax_year', 'bill_type', name='uq_tax_payment_property_year_type')
    )
    op.create_index('idx_tax_payment_bill_type', 'tax_payment_history', ['bill_type'], unique=False)
    op.create_index('idx_tax_payment_date', 'tax_payment_history', ['payment_date'], unique=False)
    op.create_index('idx_tax_payment_property_year', 'tax_payment_history', ['property_id', 'tax_year'], unique=False)
    op.create_index(op.f('ix_tax_payment_history_property_id'), 'tax_payment_history', ['property_id'], unique=False)
    # NOTE: idx_bp_pid_date_added, idx_cv_pid_date_added, idx_deeds_pid_date_added,
    # idx_score_property_date, idx_fc_pid_date_added, idx_inc_pid_date_added,
    # idx_lal_pid_date_added, idx_lp_pid_date_added, idx_td_pid_date_added,
    # idx_properties_county_id, and idx_property_normalized_address_trgm were created
    # via raw SQL in earlier migrations (fa005, fa006, fa029, ebf68e5bc028). Autogenerate
    # flags them as orphans because they are not in __table_args__; they are intentional
    # and must NOT be dropped.
    op.add_column('deeds', sa.Column('sale_qualified', sa.Boolean(), nullable=True))
    op.add_column('deeds', sa.Column('vacant_improved', sa.String(length=20), nullable=True))
    op.add_column('financials', sa.Column('exemption_code', sa.String(length=10), nullable=True))
    op.add_column('financials', sa.Column('soh_assessment_reduction', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('financials', sa.Column('taxable_value_county', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('financials', sa.Column('taxable_value_schools', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('financials', sa.Column('prior_year_market_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('financials', sa.Column('proposed_next_assessed', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('financials', sa.Column('tax_current_status', sa.String(length=20), nullable=True))
    op.add_column('financials', sa.Column('tax_last_paid_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('financials', sa.Column('tax_last_paid_date', sa.Date(), nullable=True))
    op.add_column('financials', sa.Column('hcpa_refreshed_at', sa.DateTime(), nullable=True))
    op.add_column('properties', sa.Column('property_use_code', sa.String(length=20), nullable=True))
    op.add_column('properties', sa.Column('building_condition', sa.String(length=20), nullable=True))
    op.add_column('properties', sa.Column('building_class', sa.String(length=5), nullable=True))
    op.add_column('properties', sa.Column('heated_sq_ft', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('properties', sa.Column('subdivision', sa.String(length=255), nullable=True))
    op.add_column('properties', sa.Column('hcpa_neighborhood_code', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('building_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('properties', sa.Column('hcpa_last_refreshed', sa.DateTime(), nullable=True))
    op.create_index('idx_property_building_condition', 'properties', ['building_condition'], unique=False)
    op.create_index('idx_property_building_details', 'properties', ['building_details'], unique=False, postgresql_using='gin')
    op.create_index('idx_property_hcpa_refreshed', 'properties', ['hcpa_last_refreshed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_property_hcpa_refreshed', table_name='properties')
    op.drop_index('idx_property_building_details', table_name='properties', postgresql_using='gin')
    op.drop_index('idx_property_building_condition', table_name='properties')
    op.drop_column('properties', 'hcpa_last_refreshed')
    op.drop_column('properties', 'building_details')
    op.drop_column('properties', 'hcpa_neighborhood_code')
    op.drop_column('properties', 'subdivision')
    op.drop_column('properties', 'heated_sq_ft')
    op.drop_column('properties', 'building_class')
    op.drop_column('properties', 'building_condition')
    op.drop_column('properties', 'property_use_code')
    op.drop_column('financials', 'hcpa_refreshed_at')
    op.drop_column('financials', 'tax_last_paid_date')
    op.drop_column('financials', 'tax_last_paid_amount')
    op.drop_column('financials', 'tax_current_status')
    op.drop_column('financials', 'proposed_next_assessed')
    op.drop_column('financials', 'prior_year_market_value')
    op.drop_column('financials', 'taxable_value_schools')
    op.drop_column('financials', 'taxable_value_county')
    op.drop_column('financials', 'soh_assessment_reduction')
    op.drop_column('financials', 'exemption_code')
    op.drop_column('deeds', 'vacant_improved')
    op.drop_column('deeds', 'sale_qualified')
    op.drop_index(op.f('ix_tax_payment_history_property_id'), table_name='tax_payment_history')
    op.drop_index('idx_tax_payment_property_year', table_name='tax_payment_history')
    op.drop_index('idx_tax_payment_date', table_name='tax_payment_history')
    op.drop_index('idx_tax_payment_bill_type', table_name='tax_payment_history')
    op.drop_table('tax_payment_history')
    # ### end Alembic commands ###
