"""add_recovery_day5_sent_to_subscriber

Revision ID: 92b002bd99cd
Revises: 4dd4cc27d8a9
Create Date: 2026-05-20 17:14:29.065744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92b002bd99cd'
down_revision: Union[str, Sequence[str], None] = '4dd4cc27d8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counties', sa.Column('address_city_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('subscribers', sa.Column('recovery_day5_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'recovery_day5_sent')
    op.drop_column('counties', 'address_city_tokens')
    # ### end Alembic commands ###
