"""expand_incident_type_constraint

Revision ID: ebf68e5bc028
Revises: c1d2e3f4a5b6
Create Date: 2026-03-09 11:08:22.141107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebf68e5bc028'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Expand incident_type CHECK constraint to include new scraper types
    op.drop_constraint('check_incident_type', 'incidents', type_='check')
    op.create_check_constraint(
        'check_incident_type',
        'incidents',
        "incident_type IN ('Arrest', 'Police Dispatch', 'Fire', "
        "'roofing_permit', 'storm_damage', 'flood_damage', 'insurance_claim')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_building_permits_county_id'), table_name='building_permits')
    op.drop_index(op.f('idx_building_permits_date_added'), table_name='building_permits')
    op.create_index(op.f('ix_building_permits_county_id'), 'building_permits', ['county_id'], unique=False)
    op.create_index(op.f('ix_building_permits_date_added'), 'building_permits', ['date_added'], unique=False)
    op.drop_index(op.f('idx_code_violations_county_id'), table_name='code_violations')
    op.drop_index(op.f('idx_code_violations_date_added'), table_name='code_violations')
    op.create_index(op.f('ix_code_violations_county_id'), 'code_violations', ['county_id'], unique=False)
    op.create_index(op.f('ix_code_violations_date_added'), 'code_violations', ['date_added'], unique=False)
    op.drop_index(op.f('idx_deeds_county_id'), table_name='deeds')
    op.drop_index(op.f('idx_deeds_date_added'), table_name='deeds')
    op.create_index(op.f('ix_deeds_county_id'), 'deeds', ['county_id'], unique=False)
    op.create_index(op.f('ix_deeds_date_added'), 'deeds', ['date_added'], unique=False)
    op.drop_index(op.f('idx_distress_scores_county_id'), table_name='distress_scores')
    op.drop_index(op.f('ix_distress_scores_vertical_scores'), table_name='distress_scores', postgresql_using='gin')
    op.create_index('idx_score_county_id', 'distress_scores', ['county_id'], unique=False)
    op.create_index(op.f('ix_distress_scores_county_id'), 'distress_scores', ['county_id'], unique=False)
    op.alter_column('enriched_contacts', 'match_success',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('enriched_contacts', 'enriched_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_enriched_county_id'), table_name='enriched_contacts')
    op.drop_index(op.f('idx_enriched_ghl_contact'), table_name='enriched_contacts')
    op.drop_index(op.f('idx_enriched_property_id'), table_name='enriched_contacts')
    op.create_index(op.f('ix_enriched_contacts_county_id'), 'enriched_contacts', ['county_id'], unique=False)
    op.create_index(op.f('ix_enriched_contacts_ghl_contact_id'), 'enriched_contacts', ['ghl_contact_id'], unique=False)
    op.create_index(op.f('ix_enriched_contacts_property_id'), 'enriched_contacts', ['property_id'], unique=False)
    op.drop_index(op.f('idx_financials_county_id'), table_name='financials')
    op.create_index('idx_financial_county_id', 'financials', ['county_id'], unique=False)
    op.create_index(op.f('ix_financials_county_id'), 'financials', ['county_id'], unique=False)
    op.drop_index(op.f('idx_foreclosures_county_id'), table_name='foreclosures')
    op.drop_index(op.f('idx_foreclosures_date_added'), table_name='foreclosures')
    op.create_index(op.f('ix_foreclosures_county_id'), 'foreclosures', ['county_id'], unique=False)
    op.create_index(op.f('ix_foreclosures_date_added'), 'foreclosures', ['date_added'], unique=False)
    op.alter_column('founding_subscriber_counts', 'count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('founding_subscriber_counts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_incidents_county_id'), table_name='incidents')
    op.drop_index(op.f('idx_incidents_date_added'), table_name='incidents')
    op.create_index(op.f('ix_incidents_county_id'), 'incidents', ['county_id'], unique=False)
    op.create_index(op.f('ix_incidents_date_added'), 'incidents', ['date_added'], unique=False)
    op.drop_index(op.f('idx_legal_and_liens_county_id'), table_name='legal_and_liens')
    op.drop_index(op.f('idx_legal_and_liens_date_added'), table_name='legal_and_liens')
    op.create_index(op.f('ix_legal_and_liens_county_id'), 'legal_and_liens', ['county_id'], unique=False)
    op.create_index(op.f('ix_legal_and_liens_date_added'), 'legal_and_liens', ['date_added'], unique=False)
    op.drop_index(op.f('idx_legal_proceedings_county_id'), table_name='legal_proceedings')
    op.drop_index(op.f('idx_legal_proceedings_date_added'), table_name='legal_proceedings')
    op.create_index(op.f('ix_legal_proceedings_county_id'), 'legal_proceedings', ['county_id'], unique=False)
    op.create_index(op.f('ix_legal_proceedings_date_added'), 'legal_proceedings', ['date_added'], unique=False)
    op.drop_index(op.f('idx_owner_name_trgm'), table_name='owners', postgresql_ops={'owner_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_owners_county_id'), table_name='owners')
    op.create_index('idx_owner_county_id', 'owners', ['county_id'], unique=False)
    op.create_index(op.f('ix_owners_county_id'), 'owners', ['county_id'], unique=False)
    op.drop_index(op.f('idx_properties_county_id'), table_name='properties')
    op.drop_index(op.f('idx_property_address_trgm'), table_name='properties', postgresql_ops={'address': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_property_legal_desc_trgm'), table_name='properties', postgresql_ops={'legal_description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_property_county_id', 'properties', ['county_id'], unique=False)
    op.create_index(op.f('ix_properties_county_id'), 'properties', ['county_id'], unique=False)
    op.alter_column('subscribers', 'founding_member',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscribers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscribers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscribers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_subscriber_email'), table_name='subscribers')
    op.drop_index(op.f('idx_subscriber_event_feed_uuid'), table_name='subscribers')
    op.drop_index(op.f('idx_subscriber_ghl_contact'), table_name='subscribers')
    op.drop_index(op.f('idx_subscriber_stripe_customer'), table_name='subscribers')
    op.drop_index(op.f('idx_subscriber_stripe_sub'), table_name='subscribers')
    op.drop_constraint(op.f('subscribers_event_feed_uuid_key'), 'subscribers', type_='unique')
    op.drop_constraint(op.f('subscribers_stripe_customer_id_key'), 'subscribers', type_='unique')
    op.drop_constraint(op.f('subscribers_stripe_subscription_id_key'), 'subscribers', type_='unique')
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=False)
    op.create_index(op.f('ix_subscribers_event_feed_uuid'), 'subscribers', ['event_feed_uuid'], unique=True)
    op.create_index(op.f('ix_subscribers_ghl_contact_id'), 'subscribers', ['ghl_contact_id'], unique=False)
    op.create_index(op.f('ix_subscribers_stripe_customer_id'), 'subscribers', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_subscribers_stripe_subscription_id'), 'subscribers', ['stripe_subscription_id'], unique=True)
    op.drop_index(op.f('idx_tax_delinquencies_county_id'), table_name='tax_delinquencies')
    op.drop_index(op.f('idx_tax_delinquencies_date_added'), table_name='tax_delinquencies')
    op.create_index(op.f('ix_tax_delinquencies_county_id'), 'tax_delinquencies', ['county_id'], unique=False)
    op.create_index(op.f('ix_tax_delinquencies_date_added'), 'tax_delinquencies', ['date_added'], unique=False)
    op.alter_column('zip_territories', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('zip_territories', 'waitlist_emails',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=255)),
               server_default=None,
               existing_nullable=True)
    op.alter_column('zip_territories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_zip_territory_subscriber_id'), table_name='zip_territories')
    op.create_index(op.f('ix_zip_territories_subscriber_id'), 'zip_territories', ['subscriber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Restore original incident_type CHECK constraint
    op.drop_constraint('check_incident_type', 'incidents', type_='check')
    op.create_check_constraint(
        'check_incident_type',
        'incidents',
        "incident_type IN ('Arrest', 'Police Dispatch', 'Fire')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zip_territories_subscriber_id'), table_name='zip_territories')
    op.create_index(op.f('idx_zip_territory_subscriber_id'), 'zip_territories', ['subscriber_id'], unique=False)
    op.alter_column('zip_territories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('zip_territories', 'waitlist_emails',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=255)),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=True)
    op.alter_column('zip_territories', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'available'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_tax_delinquencies_date_added'), table_name='tax_delinquencies')
    op.drop_index(op.f('ix_tax_delinquencies_county_id'), table_name='tax_delinquencies')
    op.create_index(op.f('idx_tax_delinquencies_date_added'), 'tax_delinquencies', ['date_added'], unique=False)
    op.create_index(op.f('idx_tax_delinquencies_county_id'), 'tax_delinquencies', ['county_id'], unique=False)
    op.drop_index(op.f('ix_subscribers_stripe_subscription_id'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_stripe_customer_id'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_ghl_contact_id'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_event_feed_uuid'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.create_unique_constraint(op.f('subscribers_stripe_subscription_id_key'), 'subscribers', ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('subscribers_stripe_customer_id_key'), 'subscribers', ['stripe_customer_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('subscribers_event_feed_uuid_key'), 'subscribers', ['event_feed_uuid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_subscriber_stripe_sub'), 'subscribers', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('idx_subscriber_stripe_customer'), 'subscribers', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('idx_subscriber_ghl_contact'), 'subscribers', ['ghl_contact_id'], unique=False)
    op.create_index(op.f('idx_subscriber_event_feed_uuid'), 'subscribers', ['event_feed_uuid'], unique=False)
    op.create_index(op.f('idx_subscriber_email'), 'subscribers', ['email'], unique=False)
    op.alter_column('subscribers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('subscribers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('subscribers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('subscribers', 'founding_member',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_properties_county_id'), table_name='properties')
    op.drop_index('idx_property_county_id', table_name='properties')
    op.create_index(op.f('idx_property_legal_desc_trgm'), 'properties', ['legal_description'], unique=False, postgresql_ops={'legal_description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_property_address_trgm'), 'properties', ['address'], unique=False, postgresql_ops={'address': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_properties_county_id'), 'properties', ['county_id'], unique=False)
    op.drop_index(op.f('ix_owners_county_id'), table_name='owners')
    op.drop_index('idx_owner_county_id', table_name='owners')
    op.create_index(op.f('idx_owners_county_id'), 'owners', ['county_id'], unique=False)
    op.create_index(op.f('idx_owner_name_trgm'), 'owners', ['owner_name'], unique=False, postgresql_ops={'owner_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_legal_proceedings_date_added'), table_name='legal_proceedings')
    op.drop_index(op.f('ix_legal_proceedings_county_id'), table_name='legal_proceedings')
    op.create_index(op.f('idx_legal_proceedings_date_added'), 'legal_proceedings', ['date_added'], unique=False)
    op.create_index(op.f('idx_legal_proceedings_county_id'), 'legal_proceedings', ['county_id'], unique=False)
    op.drop_index(op.f('ix_legal_and_liens_date_added'), table_name='legal_and_liens')
    op.drop_index(op.f('ix_legal_and_liens_county_id'), table_name='legal_and_liens')
    op.create_index(op.f('idx_legal_and_liens_date_added'), 'legal_and_liens', ['date_added'], unique=False)
    op.create_index(op.f('idx_legal_and_liens_county_id'), 'legal_and_liens', ['county_id'], unique=False)
    op.drop_index(op.f('ix_incidents_date_added'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_county_id'), table_name='incidents')
    op.create_index(op.f('idx_incidents_date_added'), 'incidents', ['date_added'], unique=False)
    op.create_index(op.f('idx_incidents_county_id'), 'incidents', ['county_id'], unique=False)
    op.alter_column('founding_subscriber_counts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('founding_subscriber_counts', 'count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_foreclosures_date_added'), table_name='foreclosures')
    op.drop_index(op.f('ix_foreclosures_county_id'), table_name='foreclosures')
    op.create_index(op.f('idx_foreclosures_date_added'), 'foreclosures', ['date_added'], unique=False)
    op.create_index(op.f('idx_foreclosures_county_id'), 'foreclosures', ['county_id'], unique=False)
    op.drop_index(op.f('ix_financials_county_id'), table_name='financials')
    op.drop_index('idx_financial_county_id', table_name='financials')
    op.create_index(op.f('idx_financials_county_id'), 'financials', ['county_id'], unique=False)
    op.drop_index(op.f('ix_enriched_contacts_property_id'), table_name='enriched_contacts')
    op.drop_index(op.f('ix_enriched_contacts_ghl_contact_id'), table_name='enriched_contacts')
    op.drop_index(op.f('ix_enriched_contacts_county_id'), table_name='enriched_contacts')
    op.create_index(op.f('idx_enriched_property_id'), 'enriched_contacts', ['property_id'], unique=False)
    op.create_index(op.f('idx_enriched_ghl_contact'), 'enriched_contacts', ['ghl_contact_id'], unique=False)
    op.create_index(op.f('idx_enriched_county_id'), 'enriched_contacts', ['county_id'], unique=False)
    op.alter_column('enriched_contacts', 'enriched_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('enriched_contacts', 'match_success',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_distress_scores_county_id'), table_name='distress_scores')
    op.drop_index('idx_score_county_id', table_name='distress_scores')
    op.create_index(op.f('ix_distress_scores_vertical_scores'), 'distress_scores', ['vertical_scores'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_distress_scores_county_id'), 'distress_scores', ['county_id'], unique=False)
    op.drop_index(op.f('ix_deeds_date_added'), table_name='deeds')
    op.drop_index(op.f('ix_deeds_county_id'), table_name='deeds')
    op.create_index(op.f('idx_deeds_date_added'), 'deeds', ['date_added'], unique=False)
    op.create_index(op.f('idx_deeds_county_id'), 'deeds', ['county_id'], unique=False)
    op.drop_index(op.f('ix_code_violations_date_added'), table_name='code_violations')
    op.drop_index(op.f('ix_code_violations_county_id'), table_name='code_violations')
    op.create_index(op.f('idx_code_violations_date_added'), 'code_violations', ['date_added'], unique=False)
    op.create_index(op.f('idx_code_violations_county_id'), 'code_violations', ['county_id'], unique=False)
    op.drop_index(op.f('ix_building_permits_date_added'), table_name='building_permits')
    op.drop_index(op.f('ix_building_permits_county_id'), table_name='building_permits')
    op.create_index(op.f('idx_building_permits_date_added'), 'building_permits', ['date_added'], unique=False)
    op.create_index(op.f('idx_building_permits_county_id'), 'building_permits', ['county_id'], unique=False)
    # ### end Alembic commands ###
