"""
Helper module for integrating scrapers with database loaders.

Provides a unified interface for scrapers to automatically load
their scraped data into the database.
"""

import logging
import time
from datetime import date as date_type
from pathlib import Path
from typing import Optional, Tuple

from src.core.database import get_db_context
from src.loaders import (
    ViolationLoader,
    ForeclosureLoader,
    LienLoader,
    DeedLoader,
    EvictionLoader,
    ProbateLoader,
    BuildingPermitLoader,
    BankruptcyLoader,
    TaxDelinquencyLoader,
    LisPendensLoader,
    DivorceLoader,
)
from src.loaders.tax_deed import TaxDeedAuctionLoader
from src.loaders.vacant_land import VacantParcelLoader

logger = logging.getLogger(__name__)

# Maps lien document_type labels (from lien_engine classification) to scraper_run_stats source_type keys.
# Liens arrive in one combined CSV but each row carries a document_type; stats are broken out per subtype.
LIEN_DOCTYPE_TO_SOURCE = {
    # Current label format generated by _code_lien_label in lien_engine.py
    'CODE LIENS (TCL)':         'lien_tcl',
    'CODE LIENS (CCL)':         'lien_ccl',
    # Legacy label format present in older CSVs (backfill compatibility)
    'TAMPA CODE LIENS (TCL)':   'lien_tcl',
    'COUNTY CODE LIENS (CCL)':  'lien_ccl',
    'HOA LIENS (HL)':           'lien_hoa',
    'MECHANICS LIENS (ML)':     'lien_ml',
    'TAX LIENS (TL)':           'lien_tl',
    'TAX LIEN':                 'lien_tl',   # Pinellas categorizer uses this label
}

# Maps the data_type key used by load_scraped_data_to_db → source_type stored in scraper_run_stats.
# 'liens' is handled specially (split by document_type).  'judgments' maps to its own key.
DATA_TYPE_TO_SOURCE = {
    'violations':       'violations',
    'foreclosures':     'foreclosures',
    'judgments':        'judgments',
    'deeds':            'deeds',
    'evictions':        'evictions',
    'probate':          'probate',
    'permits':          'permits',
    'bankruptcy':       'bankruptcy',
    'tax':              'tax_delinquencies',
    'lis_pendens':      'lis_pendens',
    'divorce_filings':  'divorce_filings',
    'tax_deed_auction': 'tax_deed_auction',
    'vacant_land':      'vacant_land',
}


LOADER_MAP = {
    'violations':       ViolationLoader,
    'foreclosures':     ForeclosureLoader,
    'liens':            LienLoader,
    'judgments':        LienLoader,
    'lis_pendens':      LisPendensLoader,
    'deeds':            DeedLoader,
    'evictions':        EvictionLoader,
    'probate':          ProbateLoader,
    'permits':          BuildingPermitLoader,
    'bankruptcy':       BankruptcyLoader,
    'tax':              TaxDelinquencyLoader,
    'divorce_filings':  DivorceLoader,
    'tax_deed_auction': TaxDeedAuctionLoader,
    'vacant_land':      VacantParcelLoader,
}


def record_scraper_stats(
    source_type: str,
    total_scraped: int,
    matched: int,
    unmatched: int,
    skipped: int,
    scored: int = 0,
    run_success: Optional[bool] = None,
    error_type: Optional[str] = None,
    error_message: Optional[str] = None,
    duration_seconds: Optional[float] = None,
    run_date=None,
    county_id: str = 'hillsborough',
    outcome: Optional[str] = None,
) -> None:
    """
    Upsert a row into scraper_run_stats for today's run.

    Uses INSERT … ON CONFLICT DO UPDATE so calling this multiple times
    (e.g. on retry) accumulates rather than duplicates.

    Args:
        source_type: One of the values in the check_run_stats_source_type constraint.
        total_scraped: Total rows scraped from the source.
        matched/unmatched/skipped: Loader output counts.
        scored: Number of properties rescored by CDS after this load.
        run_success: False if the run errored out. Defaults to True when
            omitted and outcome is also omitted (legacy behavior). Ignored
            (overridden) when outcome is provided — see below; omit it
            entirely on outcome-based calls so a caller that only knows the
            outcome doesn't have to separately compute the matching bool.
        error_type: 'none' | 'no_data' | 'scraper_error'. None defaults to 'none'
            on success or 'scraper_error' on failure when not explicitly set,
            UNLESS outcome is provided, in which case it defaults from
            config.scraper_outcomes.LEGACY_ERROR_TYPE_MAP instead. Passing
            both keeps this exact string (legacy reader compatibility, e.g.
            a more specific 'rate_limited') while outcome_category still
            records the real category.
        error_message: Short error description on failure.
        duration_seconds: Wall-clock seconds for the load+rescore step.
        run_date: datetime.date; defaults to today.
        county_id: County this run applies to.
        outcome: One of config.scraper_outcomes.ScraperOutcome's values (or
            None for a clean success with real data) — see
            src.utils.scraper_outcome_classifier for how to derive this from
            a caught exception instead of hand-picking error_type. When
            provided, run_success is FORCED to
            config.scraper_outcomes.derive_run_success(outcome), regardless
            of what run_success was passed — this is what makes run_success
            trustworthy by construction for migrated call sites (a caller
            can no longer claim run_success=True while outcome=TIMEOUT).
    """
    from sqlalchemy.dialects.postgresql import insert as pg_insert
    from config.scraper_outcomes import OUTCOME_VALUES, LEGACY_ERROR_TYPE_MAP, derive_run_success
    from src.core.models import ScraperRunStats

    if run_date is None:
        run_date = date_type.today()

    if outcome is not None:
        if outcome not in OUTCOME_VALUES:
            raise ValueError(f"record_scraper_stats: unknown outcome {outcome!r}")
        derived_success = derive_run_success(outcome)
        # run_success defaults to None (not passed) — only warn when the
        # caller explicitly passed a value that disagrees with the derived
        # one. Comparing against the plain bool default of True would fire
        # on every outcome-based call that (correctly) omits run_success,
        # since True != derived_success for every non-NO_DATA outcome.
        if run_success is not None and run_success != derived_success:
            logger.warning(
                "record_scraper_stats: %s/%s passed run_success=%s but outcome=%s implies %s "
                "— using the derived value",
                source_type, county_id, run_success, outcome, derived_success,
            )
        run_success = derived_success
        if error_type is None:
            error_type = LEGACY_ERROR_TYPE_MAP[outcome]
    else:
        if run_success is None:
            run_success = True  # legacy default, unchanged for callers not yet migrated
        if error_type is None:
            # Legacy default-derivation, unchanged for callers not yet migrated.
            error_type = 'none' if run_success else 'scraper_error'

    try:
        from sqlalchemy import func
        with get_db_context() as session:
            stmt = pg_insert(ScraperRunStats).values(
                run_date=run_date,
                source_type=source_type,
                county_id=county_id,
                total_scraped=total_scraped,
                matched=matched,
                unmatched=unmatched,
                skipped=skipped,
                scored=scored,
                run_success=run_success,
                error_type=error_type,
                error_message=error_message,
                duration_seconds=duration_seconds,
                outcome_category=outcome,
                completed_at=func.now(),
                updated_at=func.now(),
            )
            # On re-run within the same day (e.g. 3x/day permits, retries),
            # ACCUMULATE counts instead of overwriting them.  Matches the
            # docstring contract; previous behaviour silently dropped earlier
            # runs.  Notes on the non-additive columns:
            #   • duration_seconds → GREATEST so a fast retry doesn't hide a
            #     slow earlier run.
            #   • run_success → logical OR (any successful run wins).
            #   • error_type / error_message / outcome_category → keep the
            #     latest non-null value so the most recent outcome is visible
            #     (excluded is never actually NULL for error_type given the
            #     derivation above, so this is effectively last-call-wins).
            #   • completed_at → always the latest write's timestamp.
            excluded = stmt.excluded
            existing = ScraperRunStats.__table__.c
            stmt = stmt.on_conflict_do_update(
                constraint='uq_scraper_run_stats',
                set_=dict(
                    total_scraped=existing.total_scraped + excluded.total_scraped,
                    matched=existing.matched + excluded.matched,
                    unmatched=existing.unmatched + excluded.unmatched,
                    skipped=existing.skipped + excluded.skipped,
                    scored=existing.scored + excluded.scored,
                    run_success=existing.run_success.op('OR')(excluded.run_success),
                    error_type=func.coalesce(excluded.error_type, existing.error_type),
                    error_message=func.coalesce(excluded.error_message, existing.error_message),
                    # NOT coalesced, unlike error_type/error_message — outcome_category
                    # must reflect the MOST RECENT call's classification unconditionally,
                    # including clearing back to NULL when that call is a real success.
                    # A coalesce here would let a stale TIMEOUT/etc. from an earlier
                    # same-day attempt survive a later genuine success indefinitely,
                    # since a success call passes outcome=None (a real None, not a
                    # derived non-null value the way error_type always gets one).
                    outcome_category=excluded.outcome_category,
                    duration_seconds=func.greatest(
                        func.coalesce(existing.duration_seconds, 0),
                        func.coalesce(excluded.duration_seconds, 0),
                    ),
                    completed_at=excluded.completed_at,
                    updated_at=excluded.updated_at,
                )
            )
            session.execute(stmt)
            session.commit()
            logger.info(f"✓ Scraper stats recorded: {source_type} | scraped={total_scraped} matched={matched} unmatched={unmatched} skipped={skipped} scored={scored}")
    except Exception as e:
        logger.warning(f"⚠ Could not record scraper stats for {source_type} (non-critical): {e}")


def mark_scraper_attempt_started(
    source_type: str,
    county_id: str = 'hillsborough',
    run_date=None,
) -> None:
    """
    Stamp attempt_started_at for today's (run_date, source_type, county_id)
    row — a heartbeat independent of the completion write, so "genuinely
    never ran" (no row, attempt_started_at never set) can finally be told
    apart from "ran and crashed before ever reaching record_scraper_stats"
    (attempt_started_at set, completed_at still NULL). Called by
    src.utils.scraper_run_tracking.scraper_run()'s __enter__, before any
    network/browser work begins.

    Always overwrites to the most recent attempt, matching this table's
    existing "latest write wins" convention for completed_at/updated_at — a
    later successful retry clears an earlier attempt's apparent crash rather
    than leaving a stale, resolved alarm.

    Never raises — a heartbeat failing to write must not block the scrape
    it's timing.
    """
    from sqlalchemy.dialects.postgresql import insert as pg_insert
    from sqlalchemy import func
    from src.core.models import ScraperRunStats

    if run_date is None:
        run_date = date_type.today()

    try:
        with get_db_context() as session:
            # run_success=False (not the column's own True default) — this row
            # exists only to mark "an attempt began." If the process crashes
            # hard before ever reaching record_scraper_stats(), this row must
            # NOT read as a confirmed fresh success; it must read as exactly
            # what it is, an unfinished attempt. A later real success this
            # same day flips it True via record_scraper_stats()'s OR-merge.
            stmt = pg_insert(ScraperRunStats).values(
                run_date=run_date,
                source_type=source_type,
                county_id=county_id,
                total_scraped=0, matched=0, unmatched=0, skipped=0, scored=0,
                run_success=False,
                attempt_started_at=func.now(),
                updated_at=func.now(),
            )
            stmt = stmt.on_conflict_do_update(
                constraint='uq_scraper_run_stats',
                set_={
                    "attempt_started_at": stmt.excluded.attempt_started_at,
                    "updated_at": stmt.excluded.updated_at,
                    # Reset on every heartbeat, not just the first insert of
                    # the day — without this, a source scraped more than
                    # once per run_date (e.g. permit_engine.py, 3x/day) keeps
                    # an earlier run's completed_at timestamp on this row
                    # even after a later run starts. If that later run then
                    # crashes before its own completion write,
                    # completed_at IS NOT NULL still holds (from the earlier
                    # run), so check_crashed_before_completion() never
                    # matches it — the exact crash it exists to catch
                    # becomes invisible. Found in PR review.
                    "completed_at": None,
                },
            )
            session.execute(stmt)
            session.commit()
    except Exception as e:
        logger.warning(f"⚠ Could not mark scraper attempt started for {source_type} (non-critical): {e}")


def mark_scraper_attempt_completed(
    source_type: str,
    county_id: str = 'hillsborough',
    run_date=None,
) -> None:
    """
    Stamp completed_at (and flip run_success True) for today's
    (run_date, source_type, county_id) row WITHOUT touching total_scraped/
    matched/unmatched/skipped/outcome_category — for a caller whose real
    outcome data was already written to a *different* row (e.g.
    lien_engine.py's per-subtype rows via load_scraped_data_to_db(), while
    this aggregate row is source_type='lien_unknown') and only needs to
    signal "this attempt finished" without a misleading duplicate/empty
    aggregate.

    This is what src.utils.scraper_run_tracking.ScraperRun.suppress_completion_write()
    calls instead of leaving completed_at permanently NULL. A permanently-
    NULL completed_at is indistinguishable from a genuine crash to
    src.agents.vera.checks.live_state.check_crashed_before_completion() —
    every successful suppressed run would eventually get flagged "crashed"
    once enough time passed, which is exactly the false-alarm failure mode
    this whole classification system exists to close.

    Never raises — a completion marker failing to write must not block the
    scrape it's timing.
    """
    from sqlalchemy.dialects.postgresql import insert as pg_insert
    from sqlalchemy import func
    from src.core.models import ScraperRunStats

    if run_date is None:
        run_date = date_type.today()

    try:
        with get_db_context() as session:
            stmt = pg_insert(ScraperRunStats).values(
                run_date=run_date,
                source_type=source_type,
                county_id=county_id,
                total_scraped=0, matched=0, unmatched=0, skipped=0, scored=0,
                run_success=True,
                completed_at=func.now(),
                updated_at=func.now(),
            )
            stmt = stmt.on_conflict_do_update(
                constraint='uq_scraper_run_stats',
                set_={
                    "run_success": stmt.excluded.run_success,
                    "completed_at": stmt.excluded.completed_at,
                    "updated_at": stmt.excluded.updated_at,
                },
            )
            session.execute(stmt)
            session.commit()
    except Exception as e:
        logger.warning(f"⚠ Could not mark scraper attempt completed for {source_type} (non-critical): {e}")


def load_scraped_data_to_db(
    data_type: str,
    csv_path: Path,
    destination_dir: Optional[Path] = None,
    skip_duplicates: bool = True,
    sample_mode: bool = False,
    county_id: str = "hillsborough",
) -> Tuple[int, int, int]:
    """
    Load scraped CSV data into database using appropriate loader.

    After successful database insertion, rotates CSV archives to prevent
    storage buildup (moves new/ → old/, deletes old archives).

    Args:
        data_type: Type of data ('violations', 'foreclosures', 'liens', etc.)
        csv_path: Path to the CSV file to load
        destination_dir: Base directory containing old/ and new/ subdirectories
                        (required for CSV rotation after successful load)
        skip_duplicates: Skip existing records
        sample_mode: Load only sample data (for testing)

    Returns:
        Tuple of (matched, unmatched, skipped)

    Raises:
        ValueError: If data_type is unknown
        Exception: If database load fails
    """
    if data_type not in LOADER_MAP:
        raise ValueError(f"Unknown data type: {data_type}. Available: {list(LOADER_MAP.keys())}")

    logger.info("\n" + "=" * 60)
    logger.info(f"Loading {data_type} into database...")
    logger.info(f"CSV file: {csv_path}")
    logger.info("=" * 60)

    t_start = time.monotonic()

    try:
        with get_db_context() as session:
            loader_class = LOADER_MAP[data_type]
            loader = loader_class(session, county_id)

            loader_kwargs = {'skip_duplicates': skip_duplicates}
            if sample_mode:
                loader_kwargs['sample_mode'] = True
                logger.info("🧪 SAMPLE MODE enabled")

            matched, unmatched, skipped = loader.load_from_csv(
                str(csv_path),
                **loader_kwargs
            )
            session.commit()

            # Print summary
            logger.info(f"\n{'='*60}")
            logger.info(f"DATABASE LOAD SUMMARY - {data_type.upper()}")
            logger.info(f"{'='*60}")
            logger.info(f"  Matched:   {matched:>6}")
            logger.info(f"  Unmatched: {unmatched:>6}")
            logger.info(f"  Skipped:   {skipped:>6}")

            total = matched + unmatched + skipped
            match_rate = (matched / total * 100) if total > 0 else 0
            logger.info(f"  Match Rate: {match_rate:>5.1f}%")
            logger.info(f"{'='*60}\n")

            logger.info("✓ Database load completed!")

            # ── Lis pendens second pass (liens CSV only) ───────────────
            # The same Clerk CSV contains LP (Lis Pendens) document types.
            # LienLoader skips them; run LisPendensLoader on the same file
            # before it is deleted so early foreclosure signals are captured.
            lp_stats = {'matched': 0, 'unmatched': 0, 'skipped': 0}
            if data_type == 'liens' and csv_path.exists():
                try:
                    with get_db_context() as lp_session:
                        lp_loader = LisPendensLoader(lp_session, county_id)
                        lp_m, lp_u, lp_s = lp_loader.load_from_csv(
                            str(csv_path),
                            skip_duplicates=skip_duplicates,
                        )
                        lp_session.commit()
                        lp_stats = {'matched': lp_m, 'unmatched': lp_u, 'skipped': lp_s}
                        lp_total = lp_m + lp_u + lp_s
                        logger.info(
                            f"Lis Pendens pass: {lp_m} matched, "
                            f"{lp_u} unmatched, {lp_s} skipped "
                            f"(of {lp_total} LP records in CSV)"
                        )
                        # Merge affected IDs so the rescore step below covers LP matches
                        for pid in lp_loader.get_affected_property_ids():
                            loader._affected_property_ids.add(pid)
                except Exception as lp_err:
                    logger.warning(f"⚠ LisPendensLoader second pass failed (non-critical): {lp_err}")

            # Delete CSV after successful DB insertion; keep it on error for debugging
            try:
                csv_path.unlink()
                logger.info(f"✓ CSV deleted after successful DB insertion: {csv_path.name}")
            except Exception as e:
                logger.warning(f"⚠ Could not delete CSV (non-critical): {e}")

            # Ingestion-time rescoring: rescore only the properties touched by
            # this scraper run so scores are always up-to-date in real time.
            affected_ids = loader.get_affected_property_ids()
            scored = 0
            if affected_ids:
                logger.info(f"Triggering CDS rescore for {len(affected_ids)} affected properties...")
                try:
                    from src.services.cds_engine import MultiVerticalScorer
                    with get_db_context() as score_session:
                        scorer = MultiVerticalScorer(score_session)
                        scorer.score_properties_by_ids(affected_ids, save_to_db=True, county_id=county_id)
                        score_session.commit()
                    scored = len(affected_ids)
                    logger.info("✓ CDS rescore completed")
                except Exception as score_err:
                    logger.warning(f"⚠ CDS rescore failed (non-critical): {score_err}")
            else:
                logger.debug("No matched properties to rescore")

            duration = round(time.monotonic() - t_start, 2)

            # ── Record per-source stats ────────────────────────────────
            if data_type == 'liens':
                # Liens CSV has mixed document types; stats are split per subtype
                # using per-document_type counts captured by the loader.
                lien_counts = getattr(loader, 'stats_by_doc_type', {})
                if lien_counts:
                    # Aggregate by source_type FIRST so multiple doc_type labels mapping
                    # to the same source_type (or to the 'lien_unknown' fallback) don't
                    # overwrite each other via the (date, source_type, county) upsert.
                    agg: dict[str, dict] = {}
                    for doc_type_label, counts in lien_counts.items():
                        src = LIEN_DOCTYPE_TO_SOURCE.get(doc_type_label)
                        if src is None:
                            logger.warning(
                                "Unknown lien doc_type label %r — routing to 'lien_unknown'. "
                                "Add it to LIEN_DOCTYPE_TO_SOURCE if it should map to a real subtype.",
                                doc_type_label,
                            )
                            src = 'lien_unknown'
                        bucket = agg.setdefault(src, {'total': 0, 'matched': 0, 'unmatched': 0, 'skipped': 0})
                        bucket['total']     += counts.get('total', 0)
                        bucket['matched']   += counts.get('matched', 0)
                        bucket['unmatched'] += counts.get('unmatched', 0)
                        bucket['skipped']   += counts.get('skipped', 0)

                    total_lien_matched = sum(b['matched'] for b in agg.values())
                    for src, bucket in agg.items():
                        subtype_scored = (
                            round(scored * bucket['matched'] / total_lien_matched)
                            if total_lien_matched else 0
                        )
                        record_scraper_stats(
                            source_type=src,
                            total_scraped=bucket['total'],
                            matched=bucket['matched'],
                            unmatched=bucket['unmatched'],
                            skipped=bucket['skipped'],
                            scored=subtype_scored,
                            duration_seconds=duration,
                            county_id=county_id,
                        )
                    # Write no_data rows for expected subtypes absent from today's combined download
                    # so load_validator always sees a row for every subtype (e.g. lien_tcl on days
                    # with zero Tampa Code Liens in the county portal export).
                    from config.scraper_outcomes import ScraperOutcome
                    for src in set(LIEN_DOCTYPE_TO_SOURCE.values()):
                        if src not in agg:
                            record_scraper_stats(
                                source_type=src,
                                total_scraped=0,
                                matched=0,
                                unmatched=0,
                                skipped=0,
                                scored=0,
                                outcome=ScraperOutcome.NO_DATA.value,
                                duration_seconds=duration,
                                county_id=county_id,
                            )
                else:
                    # Loader doesn't expose per-type breakdown; record aggregate under a generic key
                    record_scraper_stats(
                        source_type='lien_ml',  # placeholder when breakdown unavailable
                        total_scraped=total,
                        matched=matched,
                        unmatched=unmatched,
                        skipped=skipped,
                        scored=scored,
                        duration_seconds=duration,
                        county_id=county_id,
                    )
                # Record lis pendens stats separately
                lp_total = lp_stats['matched'] + lp_stats['unmatched'] + lp_stats['skipped']
                if lp_total > 0:
                    record_scraper_stats(
                        source_type='lis_pendens',
                        total_scraped=lp_total,
                        matched=lp_stats['matched'],
                        unmatched=lp_stats['unmatched'],
                        skipped=lp_stats['skipped'],
                        scored=lp_stats['matched'],  # all matched LP records trigger a rescore
                        duration_seconds=duration,
                        county_id=county_id,
                    )
            else:
                source_type_key = DATA_TYPE_TO_SOURCE.get(data_type)
                if source_type_key:
                    record_scraper_stats(
                        source_type=source_type_key,
                        total_scraped=total,
                        matched=matched,
                        unmatched=unmatched,
                        skipped=skipped,
                        scored=scored,
                        duration_seconds=duration,
                        county_id=county_id,
                    )

            return matched, unmatched, skipped

    except Exception as e:
        from src.utils.scraper_outcome_classifier import classify_exception
        duration = round(time.monotonic() - t_start, 2)
        # No hardcoded run_success=False here on purpose: a ScraperNoDataError
        # reaching this generic except (no loader raises it today, but this
        # is the shared load path for every data_type in LOADER_MAP, so a
        # future one plausibly could) legitimately means a confirmed no-data
        # day, and forcing False would misreport it as a failure — the exact
        # bug class this whole classification system exists to close, found
        # via the same self-contradiction here: this block already computed
        # error_type='no_data' for that case while still hardcoding
        # run_success=False right next to it.
        outcome = classify_exception(e)
        # Record the failure in stats (non-critical — don't let it mask original error)
        source_type_key = DATA_TYPE_TO_SOURCE.get(data_type)
        if source_type_key:
            record_scraper_stats(
                source_type=source_type_key,
                total_scraped=0,
                matched=0,
                unmatched=0,
                skipped=0,
                scored=0,
                outcome=outcome,
                error_message=str(e)[:500],
                duration_seconds=duration,
                county_id=county_id,
            )
        logger.error(f"✗ Database load failed: {e}")
        import traceback
        logger.debug(traceback.format_exc())
        raise


def get_daily_scrape_counts(target_date=None):
    """
    Return a dict of {table_name: record_count} for records scraped on target_date.

    Uses the date_added field on each signal table. Defaults to today if not specified.

    Args:
        target_date: datetime.date or None (defaults to today)

    Returns:
        dict with table names as keys, counts as values, plus '_total' and '_date' keys.

    Example:
        >>> counts = get_daily_scrape_counts()
        >>> print(counts)
        {'code_violations': 45, 'deeds': 120, ..., '_total': 389, '_date': '2026-03-03'}
    """
    from src.core.models import (
        CodeViolation, LegalAndLien, Deed, LegalProceeding,
        TaxDelinquency, Foreclosure, BuildingPermit, Incident,
    )

    if target_date is None:
        target_date = date_type.today()

    TABLE_MODELS = {
        'code_violations':  CodeViolation,
        'legal_and_liens':  LegalAndLien,
        'deeds':            Deed,
        'legal_proceedings': LegalProceeding,
        'tax_delinquencies': TaxDelinquency,
        'foreclosures':     Foreclosure,
        'building_permits': BuildingPermit,
        'incidents':        Incident,
    }

    with get_db_context() as session:
        counts = {}
        for table_name, model in TABLE_MODELS.items():
            counts[table_name] = session.query(model).filter(
                model.date_added == target_date
            ).count()

    counts['_total'] = sum(v for k, v in counts.items() if not k.startswith('_'))
    counts['_date'] = str(target_date)
    return counts


def print_daily_scrape_report(target_date=None):
    """Print a formatted daily scrape count report to the log."""
    counts = get_daily_scrape_counts(target_date)
    logger.info("=" * 50)
    logger.info(f"DAILY SCRAPE COUNTS — {counts['_date']}")
    logger.info("=" * 50)
    for table, count in counts.items():
        if not table.startswith('_'):
            logger.info(f"  {table:<20} {count:>6}")
    logger.info("-" * 50)
    logger.info(f"  {'TOTAL':<20} {counts['_total']:>6}")
    logger.info("=" * 50)


def add_load_to_db_arg(parser):
    """
    Add --load-to-db argument to an argparse parser.
    
    Args:
        parser: argparse.ArgumentParser instance
        
    Returns:
        The modified parser
    """
    parser.add_argument(
        "--load-to-db",
        action="store_true",
        help="Automatically load scraped data into database after scraping"
    )
    return parser
